// Copyright (c) 2026 Robin Mordasiewicz. MIT License.

/**
 * Constants generator for F5 XC extension.
 *
 * Generates consolidated constants file with:
 * - Built-in namespaces
 * - API endpoints
 * - Category icons mapping
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Built-in namespace names that are always present in F5 XC
 */
export const BUILT_IN_NAMESPACES = ['system', 'shared', 'default'] as const;

/**
 * API endpoint definitions
 */
export const API_ENDPOINTS = {
  NAMESPACES: '/api/web/namespaces',
  CONFIG_BASE: '/api/config',
  WEB_BASE: '/api/web',
} as const;

/**
 * Category to icon mapping for tree view display.
 * Icons are VSCode Codicon names.
 */
export const CATEGORY_ICONS: Record<string, string> = {
  'Load Balancing': 'git-branch',
  Security: 'shield',
  Networking: 'globe',
  Sites: 'server',
  'Cloud Connect': 'cloud',
  DNS: 'globe',
  Observability: 'graph',
  'Identity & Access': 'key',
  'Bot Defense': 'shield',
  'API Protection': 'lock',
  'Data Protection': 'database',
  'Edge Stack': 'layers',
  'Service Mesh': 'type-hierarchy',
  'Multi-Cloud': 'cloud',
  Configuration: 'settings-gear',
};

/**
 * Generate the constants.ts file content
 */
export function generateConstantsContent(): string {
  return `/**
 * Auto-generated constants from F5 XC specifications.
 * DO NOT EDIT - This file is generated by scripts/generate-resource-types.ts
 */

/**
 * Built-in namespace names that are always present in F5 XC.
 * These namespaces have special meaning and behavior in the system.
 */
export const BUILT_IN_NAMESPACES = ${JSON.stringify(BUILT_IN_NAMESPACES, null, 2)} as const;

/**
 * Type for built-in namespace names
 */
export type BuiltInNamespace = typeof BUILT_IN_NAMESPACES[number];

/**
 * API endpoint constants for F5 XC REST API.
 * These endpoints are used across the extension for API calls.
 */
export const API_ENDPOINTS = ${JSON.stringify(API_ENDPOINTS, null, 2)} as const;

/**
 * Category to VSCode Codicon icon name mapping.
 * Used for displaying icons in the tree view based on resource category.
 */
export const CATEGORY_ICONS: Record<string, string> = ${JSON.stringify(CATEGORY_ICONS, null, 2)};

/**
 * Get the icon name for a category.
 * Returns a default icon if the category is not found.
 *
 * @param category - The resource category name
 * @returns The VSCode Codicon icon name
 */
export function getCategoryIcon(category: string): string {
  return CATEGORY_ICONS[category] || 'file';
}

/**
 * Check if a namespace name is a built-in namespace.
 *
 * @param name - The namespace name to check
 * @returns true if the namespace is built-in
 */
export function isBuiltInNamespace(name: string): boolean {
  return (BUILT_IN_NAMESPACES as readonly string[]).includes(name);
}
`;
}

/**
 * Write the generated constants file
 */
export function writeConstantsFile(outputPath: string): void {
  const content = generateConstantsContent();
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Generated: ${outputPath}`);
}
