/**
 * Resource type generator for F5 XC extension.
 *
 * Generates the base resource types from OpenAPI specifications.
 * These generated types serve as the foundation that can be extended
 * with manual overrides for UI-specific properties like icons and categories.
 */

import * as fs from 'fs';
import * as path from 'path';
import { ParsedSpecInfo, parseAllSpecs, NamespaceScope } from './spec-parser';

// Re-export types for use by other modules
export { ParsedSpecInfo, NamespaceScope } from './spec-parser';

/**
 * Generated resource type interface matching what can be extracted from specs
 */
export interface GeneratedResourceTypeInfo {
  /** API path suffix (e.g., 'http_loadbalancers') */
  apiPath: string;
  /** Display name for UI */
  displayName: string;
  /** Description from spec */
  description: string;
  /** API base: 'config' or 'web' */
  apiBase: 'config' | 'web';
  /** Full API path pattern */
  fullApiPath: string;
  /** Schema file name */
  schemaFile: string;
  /** Schema ID */
  schemaId: string;
  /** Whether resource is namespace-scoped */
  namespaceScoped: boolean;
  /** Namespace scope - derived from API path patterns */
  namespaceScope: NamespaceScope;
  /** Documentation URL */
  documentationUrl?: string;
}

/**
 * Convert parsed spec info to generated resource type info
 */
function toGeneratedTypeInfo(info: ParsedSpecInfo): GeneratedResourceTypeInfo {
  return {
    apiPath: info.apiPath,
    displayName: info.displayName,
    description: info.description,
    apiBase: info.apiBase,
    fullApiPath: info.fullApiPath,
    schemaFile: info.schemaFile,
    schemaId: info.schemaId,
    namespaceScoped: info.namespaceScoped,
    namespaceScope: info.namespaceScope,
    documentationUrl: info.documentationUrl,
  };
}

/**
 * Generate the resourceTypesBase.ts file content
 */
export function generateResourceTypesContent(specs: ParsedSpecInfo[]): string {
  const timestamp = new Date().toISOString();

  // Build the GENERATED_RESOURCE_TYPES object
  const resourceTypes: Record<string, GeneratedResourceTypeInfo> = {};
  for (const spec of specs) {
    resourceTypes[spec.resourceKey] = toGeneratedTypeInfo(spec);
  }

  // Build the API_PATH_TO_RESOURCE_KEY reverse lookup
  const apiPathToKey: Record<string, string> = {};
  for (const spec of specs) {
    apiPathToKey[spec.apiPath] = spec.resourceKey;
  }

  // Pretty print with proper TypeScript formatting
  const resourceTypesJson = JSON.stringify(resourceTypes, null, 2)
    .replace(/"([^"]+)":/g, '$1:') // Remove quotes from keys
    .replace(/: "config"/g, ": 'config'") // Use single quotes for string literals
    .replace(/: "web"/g, ": 'web'");

  const apiPathToKeyJson = JSON.stringify(apiPathToKey, null, 2).replace(/"([^"]+)":/g, "'$1':"); // Use single quotes for keys

  return `/**
 * Auto-generated resource types from F5 XC OpenAPI specifications.
 * DO NOT EDIT - This file is generated by scripts/generate-resource-types.ts
 *
 * Generated at: ${timestamp}
 * Total resource types: ${specs.length}
 */

/**
 * Namespace scope type - which namespaces can contain this resource
 * - 'any': Available in all namespaces (parameterized paths or tenant-level)
 * - 'system': Only available in system namespace (literal /namespaces/system/ paths)
 * - 'shared': Only available in shared namespace (literal /namespaces/shared/ paths)
 */
export type NamespaceScope = 'any' | 'system' | 'shared';

/**
 * Information about a generated resource type.
 * Contains data that can be extracted directly from OpenAPI specs.
 */
export interface GeneratedResourceTypeInfo {
  /** API path suffix (e.g., 'http_loadbalancers') */
  apiPath: string;
  /** Display name for UI */
  displayName: string;
  /** Description from spec */
  description: string;
  /** API base: 'config' or 'web' */
  apiBase: 'config' | 'web';
  /** Full API path pattern */
  fullApiPath: string;
  /** Schema file name */
  schemaFile: string;
  /** Schema ID (e.g., 'ves.io.schema.views.http_loadbalancer') */
  schemaId: string;
  /** Whether resource is namespace-scoped */
  namespaceScoped: boolean;
  /** Namespace scope - derived from API path patterns */
  namespaceScope: NamespaceScope;
  /** Documentation URL */
  documentationUrl?: string;
}

/**
 * Auto-generated resource types from OpenAPI specifications.
 * This is the base data that gets merged with manual overrides.
 */
export const GENERATED_RESOURCE_TYPES: Record<string, GeneratedResourceTypeInfo> = ${resourceTypesJson};

/**
 * Reverse lookup: API path suffix -> resource key
 * Useful for parsing API responses back to resource types.
 */
export const API_PATH_TO_RESOURCE_KEY: Record<string, string> = ${apiPathToKeyJson};

/**
 * Get the resource key from an API path suffix.
 *
 * @param apiPath - The API path suffix (e.g., 'http_loadbalancers')
 * @returns The resource key or undefined if not found
 */
export function getResourceKeyFromApiPath(apiPath: string): string | undefined {
  return API_PATH_TO_RESOURCE_KEY[apiPath];
}

/**
 * Get the generated resource type info for a key.
 *
 * @param key - The resource key (e.g., 'http_loadbalancer')
 * @returns The generated resource type info or undefined
 */
export function getGeneratedResourceType(key: string): GeneratedResourceTypeInfo | undefined {
  return GENERATED_RESOURCE_TYPES[key];
}

/**
 * Get all generated resource type keys.
 *
 * @returns Array of all resource type keys
 */
export function getAllGeneratedResourceKeys(): string[] {
  return Object.keys(GENERATED_RESOURCE_TYPES);
}
`;
}

/**
 * Generate resource types from spec files and write to output file
 */
export function generateResourceTypesFile(specDir: string, outputPath: string): ParsedSpecInfo[] {
  const specs = parseAllSpecs(specDir);

  if (specs.length === 0) {
    console.error('No specs parsed successfully');
    return [];
  }

  const content = generateResourceTypesContent(specs);
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Generated: ${outputPath} with ${specs.length} resource types`);

  return specs;
}
